language: android
 
before_script: 
 - cd GymCompanion
 - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-28
